/*
  Genentech Colors:
  #004B8C	Genentech Blue (294)
  #F5CC06	Genentech Yellow (123)
  #FF9900	Genentech Orange (144)
  #E1293E	Genentech Red (1795)
  #913745	Genentech Maroon (202)
  #8CD5F9	Genentech Light Blue (297)
  #496A08	Genentech Green (371)
  #B7D98B	Genentech Light Green (367)
  #150067	Genentech Blue (old)
*/


U_BG=white
U_CODE_BG=white
U_DEBUG_BG=white
U_ERROR_FG=red
U_FRAME=#004B8C
U_HOVER_HIGHLIGHT=#F5CC06
U_HOVER_HIGHLIGHT_BG=#F5CC06
U_HOVER_HIGHLIGHT_FG=U_FRAME
U_IMPORTANT_BG=red
U_IMPORTANT_FG=red
U_NAV_BG=white
U_NAV_FG=U_FRAME
U_NAV_SELECTED_BG=U_FRAME
U_NAV_SELECTED_FG=white
U_POPUP_BG=#F5CC06
U_POPUP_FG=black
U_POPUP_FRAME=black
U_SELECTED=#F5CC06
U_SQL_BG=#B7D9BB
U_SQL_FG=black
U_TABLE_BG=white
U_TABLE_FG=U_FRAME
U_TABLE_HIGHLIGHT_BG=#F5CC06
U_TABLE_HIGHLIGHT_FG=black
U_TABLE_TH_BG=U_FRAME
U_TABLE_TH_FG=white
U_TOOLTIP_BG=U_POPUP_BG
U_TOOLTIP_FG=U_POPUP_FG
U_UNHIGHLIGHTED=#004B8C
U_UWTABLE_BG=U_TABLE_BG
U_UWTABLE_FG=#913745
