# http://wellstyled.com/tools/colorscheme2/index-en.html?tetrad;100;0;75;0;1;0.5;0.75;0.1;1;0.5;1;0.25;1;0.5;0.75;0.1;1;0.5;1;0.25;1;0.5;0.75;0.1;1;0.5;1;0.25;1;0.5;0.75;0.1;1;0.5;1;0

## #FFECBF #BFA260 #FFF7E6 #FFD980
## #C8C8FF #6D6DBF #E9E9FF #9191FF
## #FFBFDC #BF608A #FFE6F1 #FF80B8
## #CCFFBF #73BF60 #EBFFE6 #99FF80


U_BG=white
U_CODE_BG=#99FF80
U_DEBUG_BG=#FF80B8
U_ERROR_FG=#BF608A
U_FRAME=#6D6DBF
U_SELECTED=#FFD980
U_UNHIGHLIGHTED=#FFFFFF


U_HOVER_HIGHLIGHT=#FFECBF
U_HOVER_HIGHLIGHT_BG=#FFECBF
U_HOVER_HIGHLIGHT_FG=black

U_IMPORTANT_BG=#FFFFFF
U_IMPORTANT_FG=#BF608A

U_LEGEND_FRAME=U_FRAME
U_LEGEND_BG=#C8C8FF
U_LEGEND_FG=black

U_NAV_BG=white
U_NAV_FG=U_FRAME
U_NAV_FRAME=U_NAV_FG
U_NAV_SELECTED_BG=U_NAV_FG
U_NAV_SELECTED_FG=U_NAV_BG
U_NAV_SELECTED_FRAME=U_NAV_FRAME
U_NAV_HOVER_BG=U_HOVER_HIGHLIGHT_BG
U_NAV_HOVER_FG=U_HOVER_HIGHLIGHT_FG
U_NAV_HOVER_FRAME=U_NAV_FRAME

U_POPUP_BG=#FFBFDC
U_POPUP_FG=black
U_POPUP_FRAME=U_POPUP_FG

U_SQL_BG=white
U_SQL_FG=#73BF60

U_TOOLTIP_BG=U_POPUP_BG
U_TOOLTIP_FG=U_POPUP_FG

U_UWTABLE_FRAME=#73BF60
U_UWTABLE_BG=white
U_UWTABLE_FG=#73BF60
U_UWTABLE_TH_FRAME=U_UWTABLE_FRAME
U_UWTABLE_TH_BG=#CCFFBF
U_UWTABLE_TH_FG=black
U_UWTABLE_TD_FRAME=U_UWTABLE_FRAME
U_UWTABLE_TD_BG=white
U_UWTABLE_TD_FG=black;
U_UWTABLE_HIGHLIGHT_FRAME=U_UWTABLE_FRAME
U_UWTABLE_HIGHLIGHT_BG=#FFD980
U_UWTABLE_HIGHLIGHT_FG=U_POPUP_FG
