#!/bin/sh -e

unset PGHOST PGUSER
export PGDATA=/scr/$PBS_JOBID/pgdata
export PGDATABASE=csb
export LANG=C

echo "PGHOST=$PGHOST"
echo "PGUSER=$PGUSER"
echo "PGDATA=$PGDATA"
echo "PGDATABASE=$PGDATABASE"

case "$PGDATA" in
	/scr/*) ;;
	*) exit "PGDATA NOT SET TO /scr/ subdirectory... bailing"; exit 2;;
esac

set -x

pg_ctl -l $PGDATA/log stop
rm -fr $PGDATA
/apps/compbio/i686-linux-2.4/opt/postgresql/bin/initdb
pg_ctl -l $PGDATA/log start
sleep 2

createuser -a -d admin
createuser -A -D loader
createdb $PGDATABASE

psql -Uadmin -c "alter database csb set search_path = '\$user',unison,scop,public"

gzip -cdq $HOME/unison/backups/csb/2003-03-08-00\:05.pgdump.gz \
 | (time -p psql -qaf-) >|$PGDATA/restore.log  2>|$PGDATA/restore.err

time -p psql -q -dcsb -c 'analyze' 
