#!/bin/sh

tbl=$1; shift;
S=${1:-1800};
echo "# monitoring entries in $tbl; sleeptime=$S"

N0= 

while true; do
	D=`date "+%Y:%m:%d %H:%M:%S"`
	N=`psql -t -htd-sprog -dunison -c "select count(*) from $tbl"`
	ds=
	if [ -n "$N0" ]; then
		Nd=$((N-N0))
		Nr=`echo "scale=5; $Nd/$S" | bc`
		ds=`printf "%5d %5.2f/s" $Nd $Nr`
	fi
	printf "$D %8d $ds\n" $N
	N0=$N
	sleep $S
done
