#!/bin/sh
# $Id: nightly,v 1.7 2004/01/08 02:17:38 rkh Exp $

# nightly -- tasks to perform nightly
# you must set PGPASSWORD before running this script

source `dirname $0`/utils


if [ -z "$PGPASSWORD" ]; then
	die "PGPASSWORD not set"
fi

V=`type -p vacuumdb`

logger "vacuum analyze started"
dothis "$V" -Ucompbio -dcsb -z
dothis "$V" -Ucompbio -dcsb-dev -z
logger "vacuum analyze done"
