#!/bin/sh
# $Id: nightly,v 1.5 2003/10/01 16:05:46 rkh Exp $

# nightly -- tasks to perform nightly
# you must set PGPASSWORD before running this script

source `dirname $0`/utils


if [ -z "$PGPASSWORD" ]; then
	die "PGPASSWORD not set"
fi


logger "vacuum analyze started"
logger `type -p vacuumdb`
dothis vacuumdb -Uadmin -dcsb -z  # -f
logger "vacuum analyze done"
