#!/bin/sh
# $Id: nightly,v 1.8 2004/02/19 23:07:28 rkh Exp $

# nightly -- tasks to perform nightly
# you must set PGPASSWORD before running this script

source `dirname $0`/utils


if [ -z "$PGPASSWORD" ]; then
	die "PGPASSWORD not set"
fi

V=`type -p vacuumdb`

logger "vacuum analyze started"
dothis "$V" -Ucompbio -dcsb-dev -z
logger "vacuum analyze done"
