#!/usr/bin/env perl
# generate sql create user statements from passwd file

use strict;
use warnings;
use Getopt::Long qw(:config gnu_getopt);
use Data::Dumper;

my %opts =
  (
   groups => undef,
  );

GetOptions(\%opts,
		   'groups|group|g=i@')
  || die("usage\n");

my %wanted_logins;

if (@ARGV) {
  if ($opts{groups}) {
	die("can't specify group and logins\n");
  }
  %wanted_logins = map { $_=>1 } @ARGV;
  undef @ARGV;
}


my %wanted_groups;
if ($opts{groups}) {
  %wanted_groups = map {$_=>1} @{$opts{groups}};
}


my %omit = map {$_=>1} 
  qw(Bioinfo gx2000-1 compbio postgres pgsql maint Molbio);

while(<>) {
  my @F = split(/:/);
  
  # don't print these under any circumstances:
  next if (exists $omit{$F[0]});			# skip login
  next if ($F[2]<=100);						# skip low-numbered uids

  if ( (%wanted_groups and exists $wanted_groups{$F[3]})
	   or (exists $wanted_logins{$F[0]}) ) {
	printf("create user $F[0] with sysid $F[2] nocreatedb nocreateuser;\n");
	delete $wanted_logins{$F[0]};
  }
}



my @remaining = sort keys %wanted_logins;
if (@remaining) {
  die(sprintf("%d login(s) weren't found: {%s}\n",
			  $#remaining+1, join(',',@remaining)));
}
exit(0);
