#!/bin/sh

unset PGHOST

if [ "`uname -n`" != "interceptor" ]; then
	echo "this should be run on interceptor" 1>&2
	exit 1
fi

if [ -z "$PGPORT" -o -z "$PGPASSWORD" -o  -z "$PGDATABASE" -o -z "PGUSER" ]; then
	echo "PGPORT, PGUSER, PGDATABASE, and PGPASSWORD must be set:" 1>&2
	echo "  PGPORT=6543 PGUSER=me PGPASSWORD=blah PGDATABASE=dbname $0" 1>&2
	exit 2
fi


# attempt to connect and fail if connection succeeds
if psql -UPUBLIC -c'\q' >/dev/null 2>/dev/null; then
	echo "$PGDATABASE already exists; aborting" 1>&2
	exit 3
fi


psql -dtemplate1 -qaf - <<EOF
create database "$PGDATABASE";
grant create on database "$PGDATABASE" to rkh;
grant create on database "$PGDATABASE" to cavs;
EOF

case "$1" in
	*.gz) GZIP= gzip -cd "$1" | /usr/bin/time -p psql -qaf -;;
	*) /usr/bin/time -p psql -qaf $1;;
esac

exit $?
