drop schema cavs CASCADE;
drop schema dali CASCADE;
drop schema gong CASCADE;
drop schema harmony CASCADE;
drop schema matthejb CASCADE;
drop schema mukhyala CASCADE;
drop schema pgutils CASCADE;
drop schema rkh CASCADE;
drop schema taxonomy CASCADE;
